-- MySQL Script generated by MySQL Workbench
-- Fri May  6 22:19:32 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Bubble
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Bubble
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Bubble` DEFAULT CHARACTER SET utf8 ;
USE `Bubble` ;

-- -----------------------------------------------------
-- Table `Bubble`.`Utilizador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bubble`.`Utilizador` (
  `IDUtilizador` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Apelido` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(13) NOT NULL,
  `tipoConta` INT NULL,
  `DataAdesao` DATE NULL,
  `DataNascimento` DATE NOT NULL,
  `EstadoConta` INT NOT NULL,
  `fotoPerfil` VARCHAR(45) NULL,
  `fotoCapa` VARCHAR(45) NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IDUtilizador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bubble`.`Publicacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bubble`.`Publicacoes` (
  `IDPub` INT NOT NULL AUTO_INCREMENT,
  `Titulo` VARCHAR(45) NOT NULL,
  `Desc` LONGTEXT NOT NULL,
  `num_comentarios` INT NULL,
  `num_likes` INT NULL,
  `DataPublicacao` DATE NOT NULL,
  `CaminhoFoto` VARCHAR(45) NULL,
  `Utilizador_IDUtilizador` INT NOT NULL,
  PRIMARY KEY (`IDPub`, `Utilizador_IDUtilizador`),
  INDEX `fk_Publicacoes_Utilizador1_idx` (`Utilizador_IDUtilizador` ASC),
  CONSTRAINT `fk_Publicacoes_Utilizador1`
    FOREIGN KEY (`Utilizador_IDUtilizador`)
    REFERENCES `Bubble`.`Utilizador` (`IDUtilizador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bubble`.`Mensagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bubble`.`Mensagens` (
  `IDMensagem` INT NOT NULL AUTO_INCREMENT,
  `DataEnvio` DATE NOT NULL,
  `Mensagem` VARCHAR(45) NOT NULL,
  `Utilizador_IDUtilizador` INT NOT NULL,
  PRIMARY KEY (`IDMensagem`, `Utilizador_IDUtilizador`),
  INDEX `fk_Mensagens_Utilizador1_idx` (`Utilizador_IDUtilizador` ASC),
  CONSTRAINT `fk_Mensagens_Utilizador1`
    FOREIGN KEY (`Utilizador_IDUtilizador`)
    REFERENCES `Bubble`.`Utilizador` (`IDUtilizador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bubble`.`Seguidores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bubble`.`Seguidores` (
  `IDPedido` INT NOT NULL AUTO_INCREMENT,
  `Destinatario` VARCHAR(45) NOT NULL,
  `Estado` VARCHAR(45) NOT NULL,
  `DataSeguidor` VARCHAR(45) NOT NULL,
  `Utilizador_IDUtilizador` INT NOT NULL,
  PRIMARY KEY (`IDPedido`, `Utilizador_IDUtilizador`),
  INDEX `fk_Amizades_Utilizador1_idx` (`Utilizador_IDUtilizador` ASC),
  CONSTRAINT `fk_Amizades_Utilizador1`
    FOREIGN KEY (`Utilizador_IDUtilizador`)
    REFERENCES `Bubble`.`Utilizador` (`IDUtilizador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bubble`.`Comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bubble`.`Comentarios` (
  `IDComentario` INT NOT NULL AUTO_INCREMENT,
  `Comentario` VARCHAR(45) NOT NULL,
  `DataComentario` VARCHAR(45) NOT NULL,
  `Utilizador_IDUtilizador` INT NOT NULL,
  PRIMARY KEY (`IDComentario`, `Utilizador_IDUtilizador`),
  INDEX `fk_Comentarios_Utilizador1_idx` (`Utilizador_IDUtilizador` ASC),
  CONSTRAINT `fk_Comentarios_Utilizador1`
    FOREIGN KEY (`Utilizador_IDUtilizador`)
    REFERENCES `Bubble`.`Utilizador` (`IDUtilizador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bubble`.`Notificacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bubble`.`Notificacoes` (
  `IDNotifi` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NULL,
  `remetente` VARCHAR(45) NULL,
  `Utilizador_IDUtilizador` INT NOT NULL,
  PRIMARY KEY (`IDNotifi`, `Utilizador_IDUtilizador`),
  INDEX `fk_Notificacoes_Utilizador1_idx` (`Utilizador_IDUtilizador` ASC),
  CONSTRAINT `fk_Notificacoes_Utilizador1`
    FOREIGN KEY (`Utilizador_IDUtilizador`)
    REFERENCES `Bubble`.`Utilizador` (`IDUtilizador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bubble`.`DefinicoesSite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bubble`.`DefinicoesSite` (
  `IDPag` INT NOT NULL AUTO_INCREMENT,
  `ficheiroCSS` VARCHAR(45) NOT NULL,
  `url` VARCHAR(45) NOT NULL,
  `tituloPag` VARCHAR(45) NOT NULL,
  `KeywordsPag` VARCHAR(45) NOT NULL,
  `descricaoSite` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IDPag`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bubble`.`FAQS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bubble`.`FAQS` (
  `IDFaq` INT NOT NULL AUTO_INCREMENT,
  `Titulo` VARCHAR(45) NOT NULL,
  `Desc` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IDFaq`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bubble`.`Empregos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bubble`.`Empregos` (
  `IDEmprego` INT NOT NULL AUTO_INCREMENT,
  `Titulo` VARCHAR(45) NOT NULL,
  `DataPub` DATE NOT NULL,
  `Localizacao` VARCHAR(45) NOT NULL,
  `Tipo` VARCHAR(20) NOT NULL,
  `Horarios` VARCHAR(45) NOT NULL,
  `Categorias` VARCHAR(45) NOT NULL,
  `SalarioMinimo` INT NULL,
  `SalarioMaximo` INT NULL,
  `Descricao` VARCHAR(255) NOT NULL,
  `Utilizador_IDUtilizador` INT NOT NULL,
  PRIMARY KEY (`IDEmprego`, `Utilizador_IDUtilizador`),
  INDEX `fk_Empregos_Utilizador1_idx` (`Utilizador_IDUtilizador` ASC),
  CONSTRAINT `fk_Empregos_Utilizador1`
    FOREIGN KEY (`Utilizador_IDUtilizador`)
    REFERENCES `Bubble`.`Utilizador` (`IDUtilizador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bubble`.`Empresas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bubble`.`Empresas` (
  `IDEmpresa` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `localizacao` VARCHAR(45) NOT NULL,
  `especialidade` VARCHAR(45) NOT NULL,
  `fotoPerfil` VARCHAR(45) NULL,
  `fotoCapa` VARCHAR(45) NULL,
  `Utilizador_IDUtilizador` INT NOT NULL,
  PRIMARY KEY (`IDEmpresa`, `Utilizador_IDUtilizador`),
  INDEX `fk_Empresas_Utilizador1_idx` (`Utilizador_IDUtilizador` ASC),
  CONSTRAINT `fk_Empresas_Utilizador1`
    FOREIGN KEY (`Utilizador_IDUtilizador`)
    REFERENCES `Bubble`.`Utilizador` (`IDUtilizador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bubble`.`Eventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bubble`.`Eventos` (
  `IDEvento` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `localizacao` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `CaminhoFoto` VARCHAR(45) NULL,
  `Utilizador_IDUtilizador` INT NOT NULL,
  PRIMARY KEY (`IDEvento`, `Utilizador_IDUtilizador`),
  INDEX `fk_Eventos_Utilizador1_idx` (`Utilizador_IDUtilizador` ASC),
  CONSTRAINT `fk_Eventos_Utilizador1`
    FOREIGN KEY (`Utilizador_IDUtilizador`)
    REFERENCES `Bubble`.`Utilizador` (`IDUtilizador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bubble`.`Comunidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bubble`.`Comunidades` (
  `IDComunidade` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `hashtag` VARCHAR(45) NOT NULL,
  `Utilizador_IDUtilizador` INT NOT NULL,
  PRIMARY KEY (`IDComunidade`, `Utilizador_IDUtilizador`),
  INDEX `fk_Comunidades_Utilizador1_idx` (`Utilizador_IDUtilizador` ASC),
  CONSTRAINT `fk_Comunidades_Utilizador1`
    FOREIGN KEY (`Utilizador_IDUtilizador`)
    REFERENCES `Bubble`.`Utilizador` (`IDUtilizador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bubble`.`Marketplace`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bubble`.`Marketplace` (
  `IDAnuncio` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `caminhoFoto` VARCHAR(45) NULL,
  `Utilizador_IDUtilizador` INT NOT NULL,
  PRIMARY KEY (`IDAnuncio`, `Utilizador_IDUtilizador`),
  INDEX `fk_Marketplace_Utilizador1_idx` (`Utilizador_IDUtilizador` ASC),
  CONSTRAINT `fk_Marketplace_Utilizador1`
    FOREIGN KEY (`Utilizador_IDUtilizador`)
    REFERENCES `Bubble`.`Utilizador` (`IDUtilizador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bubble`.`guardado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bubble`.`guardado` (
  `IDPubGuard` INT NOT NULL AUTO_INCREMENT,
  `DataGuard` DATE NULL,
  `Utilizador_IDUtilizador` INT NOT NULL,
  `Publicacoes_IDPub` INT NOT NULL,
  `Publicacoes_Utilizador_IDUtilizador` INT NOT NULL,
  PRIMARY KEY (`IDPubGuard`, `Utilizador_IDUtilizador`, `Publicacoes_IDPub`, `Publicacoes_Utilizador_IDUtilizador`),
  INDEX `fk_guardado_Utilizador1_idx` (`Utilizador_IDUtilizador` ASC),
  INDEX `fk_guardado_Publicacoes1_idx` (`Publicacoes_IDPub` ASC, `Publicacoes_Utilizador_IDUtilizador` ASC),
  CONSTRAINT `fk_guardado_Utilizador1`
    FOREIGN KEY (`Utilizador_IDUtilizador`)
    REFERENCES `Bubble`.`Utilizador` (`IDUtilizador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_guardado_Publicacoes1`
    FOREIGN KEY (`Publicacoes_IDPub` , `Publicacoes_Utilizador_IDUtilizador`)
    REFERENCES `Bubble`.`Publicacoes` (`IDPub` , `Utilizador_IDUtilizador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
